### ISSUE TITLE
Output Stan model code

### ISSUE THREAD

**Issue by jacob-long** [mvuorre/bmlm#10]
Related to my interim solution for #9, it would be great if you could either add an argument or separate function for simply printing the Stan model code to the console. Since I've wanted to tweak the model code to add covariates and a couple other things, I've had to compile the simpler model and then extract it from the stanfit object.

If you prefer, I could probably program this feature in a few minutes if you want me to just submit a pull request.

**Comment by mvuorre** [comment]
Hi,

I've purposefully left the fitted model object (output of `mlm()`) as a stanfit (`?rstan::stanfit`) object. Therefore, you can output the model code with `rstan::get_stancode()`:

```r
library(bmlm)

# Create within-subject centered mediator variable
MEC2010 <- isolate(d = MEC2010,
                   by = "subj",  
                   value = "hr")  

# Fit model
fit <- mlm(d = MEC2010, 
           id = "subj", 
           x = "lag", 
           m = "hr_cw", 
           y = "jop",
           iter = 250, cores = 4)

# Print stancode (wrapped in `cat()` for nicer output)
cat(rstan::get_stancode(fit))
```

You don't need to compile the model after installing the bmlm package, because it is compiled during installing the package. After this, you can get the code by fitting the model to data. 

You can also get the source code from github without doing any of this. The instructions for combining Stan code chunks are in [bmlm/exec](https://github.com/mvuorre/bmlm/tree/master/exec), and the chunks themselves are in [bmlm/inst/chunks](https://github.com/mvuorre/bmlm/tree/master/inst/chunks).

Because the model code is already easy to get, I would rather not add functions that would duplicate these existing ways of getting the code.

As you can see, modifying the code won't be too difficult. However, once the model is significantly changed, all the helper functions lose their functionality, because they are designed for the two fixed models that bmlm currently includes (v1.3.3).

Thanks!
