### ISSUE TITLE
error in pme estimate

### ISSUE THREAD

**Issue by MonicaFialho** [mvuorre/bmlm#16]
I've adjusted a model via `mlm` and I get the following output:

```
  Parameter     Mean       SE   Median      2.5%    97.5% n_eff     Rhat
1         a 0.303657 0.125057 0.302952  0.060824 0.550272  5088 1.000301
2         b 0.054777 0.075261 0.054739 -0.091129 0.208491  4464 0.999870
3        cp 0.213462 0.091290 0.213953  0.037554 0.392827  4986 0.999773
4        me 0.022751 0.057947 0.020770 -0.095774 0.145706  2099 1.001678
5         c 0.236213 0.093998 0.235764  0.050176 0.423339  4698 0.999930
6       pme 0.033827 1.861123 0.090808 -0.729028 0.659824  3466 1.001063
```

According to Bolger and Laurence book (2013), `pme` should be equal to `me/c` but it is not the result I get.
The result should be close to 0.10 (`0.022751 / 0.236213 = 0.09631561`).

It is possible to know how this value is being computed? Or am I missing something?

Thank you!

**Comment by mvuorre** [comment]
Hi,

`pme` is calculated appropriately as `me`/`c` as shown here https://github.com/mvuorre/bmlm/blob/1070a02bea7fdab9dde3543d0eec872afe35e7ba/inst/stan/chunks/generated_quantities.stan#L41

You are getting different numbers because you're just operating on the posterior means. If you do the operation for each sample and then summarise, you get the correct numbers.

**Comment by MonicaFialho** [comment]
Despite that, it would be correct if I report the indirect effect (me; 0.02, 95% CI: -0.10 - 0.15) to conclude on the mediation effect (not significant in this case), am I right?
Thank you for your help, @mvuorre

**Comment by mvuorre** [comment]
Yes, the indirect effect's posterior distribution indicates that zero is within the 95% most credible values.

My pleasure 😄
